version: '3.9'

networks: 
  k6:

services: 
  influxdb:
    image: influxdb:latest
    networks:
      - k6
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=k6-org
      - DOCKER_INFLUXDB_INIT_BUCKET=k6-bucket
  k6:
    image: loadimpact/k6:latest
    networks: 
      - k6
    ports: 
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6-bucket
      - K6_INFLUXDB_USERNAME=user
      - K6_INFLUXDB_PASSWORD=password      
      - K6_INFLUXDB_INSECURE=true
    volumes: 
      - ./scripts:/scripts
