version: '3.9'

networks: 
  k6:

services: 
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_BUCKET=k6bucket

  k6:
    image: loadimpact/k6:latest
    networks: 
      - k6
    ports: 
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6bucket
    volumes: 
      - ./scripts:/scripts

  grafana:
    image: grafana/grafana:latest
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/